### ISSUE TITLE
File moresql.json

### ISSUE THREAD

**Issue by forrestrunning** [zph/moresql#12]
Is there an actual working example of moresql.json?

With some refined doc, this project has a good potential...

**Comment by basitshaikh** [comment]
https://github.com/zph/moresql/blob/716da504dd68136fb8bc52c00f1fb383d8163c89/bin/convert_config_from_mosql_to_moresql#L28

**Comment by zph** [comment]
@forrestrunning Thanks for the issue. I added a sample configuration https://github.com/zph/moresql/blob/master/examples/moresql.json and updated the readme :).

**Comment by zph** [comment]
Is that enough information for you to get started when new to the project? Or what else would be helpful?

**Comment by zph** [comment]
(Closing but happy to reopen to continue the discussion and figure out how to present this information in more accessible way)
