### ISSUE TITLE
Records read from MongoDB but are skipped, not written in Potgres

### ISSUE THREAD

**Issue by ntarlapan** [zph/moresql#14]
Thank you for developing and publishing moresql tool.
I connected moresql to a local mongo database and a local Postgres database. Then I inserted some rows into Mongo. Moresql reads the rows, but skips them.

Here is my moresql file that I use:
```json
{
    "sample_db": {
       "collections": {
          "sample_collection": {
             "name": "sample_collection",
             "pg_table": "sample_table",
             "fields": {
                "_id": "TEXT",
                "hello": "TEXT"
             }
          }
       }
    }
 }```
There are such table in Postgres (I validated the schema) and the collection in Mongo (moresql reads the records) that correspond to the moresql.json file.

Here is the output from the terminal:

```bash
/moresql$ ./bin/moresql -tail -config-file=moresql.json
INFO[0000] Connected to postgres                        
INFO[0000] Connected to mongo                           
INFO[0000] Starting from epoch: 1596485394              
INFO[0000] Tailing mongo oplog                          
INFO[0060] Rate of read per min: 1                      
INFO[0060] Rate of skipped per min: 1                   
INFO[0060] Rate of insert per min: 0                    
INFO[0060] Rate of update per min: 0                    
INFO[0060] Rate of delete per min: 0              
```

What could be the cause? Could I see a more detailed description of this behavior. Maybe there is some verbose way to run moresql, so that I could see the causes of the issue. Why would rows be skipped?
Please let me know what details should I provide. Maybe I missed something.
Thank you,

**Comment by zph** [comment]
Hi @ntarlapan, my apology on the delay, I missed the notification from this repo.

Confirming the steps that you took:
- You started moresql tailing
- Inserted rows into Mongo
- Didn't see those appear in PG

Is that correct?

Your config looks correct from what I see. 

Troubleshooting questions:
- If you run `./bin/moresql -validate -config-file=moresql.json` what is the output?
- Did you run the metadata table setup SQL? https://github.com/zph/moresql#table-setup

If you're still interested to debug, I fixed my notifications here so it should arrive in my inbox :).
