### ISSUE TITLE
FATA[0000] pq: SSL is not enabled on the server   

### ISSUE THREAD

**Issue by Brice187** [zph/moresql#16]
I tried to get `moresql` to work in my kubernetes setup.

On my test pod, i can connect to the postgres db 

```
root@my-shell:/tmp# psql -h postgres-service -U moresql -d postgres
Password for user moresql: 
psql (11.9 (Debian 11.9-0+deb10u1), server 10.15 (Debian 10.15-1.pgdg90+1))
Type "help" for help.

postgres=> exit;
```
Output of moresql:
```
root@my-shell:/tmp# export POSTGRES_URL=postgresql://moresql:moresql@postgres-service:5432/postgres?sslmode=require
root@my-shell:/tmp# ./moresql -tail
FATA[0000] pq: SSL is not enabled on the server
```

Tested with PG10 and PG12 with `PGSSLMODE: require` and `None`

**Comment by zph** [comment]
@Brice187 I haven't seen that error in our setups with this library.

Here are some troubleshooting thoughts that come to mind:
- Are you able to connect to the pg instance if you set `sslmode=disable`? (You wouldn't want to do it outside debugging in case this needs to cross unprotected networks)
- I see that your psql command isn't using SSL. Can you try it with a similar query string? ie `psql "postgresql://moresql:moresql@postgres-service:5432/postgres?sslmode=require"`. (This would let us know if the connection string works for other tools)

My next question is, was PG compiled with SSL enabled? From skimming documents here it seems like that's a required step; https://www.postgresql.org/docs/9.5/ssl-tcp.html 

```
This requires that OpenSSL is installed on both client and server systems and that support in PostgreSQL is enabled at build time (see Chapter 15).
```

Please let me know if this helps and what responses you get from the commands :). I'll happily help as time allows.
